<?php

namespace Pascal\FeedGathererBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RssFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssFeedRepository extends EntityRepository
{
}