<?php

namespace Pascal\FeedGathererBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TwitterUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterUserRepository extends EntityRepository
{
}